### ISSUE TITLE
Diagram of the solution

### ISSUE THREAD

**Issue by dgomesbr** [aws-samples/amazon-chime-sdk-amazon-connect-integration-demo#2]
Diagram are a way to give customers/users an overview of the current solution; Please create a diagram for this.

**Comment by devalevenkatesh** [comment]
Sure, I will attach a diagram for better understanding. Thanks for brining it up.

**Comment by devalevenkatesh** [comment]
Attached the [diagram](https://github.com/aws-samples/amazon-chime-sdk-amazon-connect-integration-demo#diagram)
