### ISSUE TITLE
Automatic Recording and Share Screen Function

### ISSUE THREAD

**Issue by reynoldnathaniel** [aws-samples/amazon-chime-sdk-amazon-connect-integration-demo#7]
Is there a way to record automatically when the meeting is started?
Meeting Started -> Agent/Customer starts recording -> Agent/Customer send video to Amazon S3

Also, I see that there is a share screen function. Are there any future implementation in this Github for Agent and Customer share screen?

**Comment by devalevenkatesh** [comment]
Hello,

 There is currently no way to record but you can implement it by following our [recording demo](https://github.com/aws-samples/amazon-chime-sdk-recording-demo) and a [blog post](https://aws.amazon.com/blogs/business-productivity/how-to-enable-client-side-recording-using-the-amazon-chime-sdk/).

The screen share is just an display icon for now and does not do anything. You can extend that functionality following our JS SDK demo which shows content sharing capabilities.
Helpful links:
1. Our README explains how to add content share [here](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share).
2. [Content share guide](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/02_Content_Share.md).
3. Amazon Chime JS SDK Demo:
3.1 [Add content share](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1295).
3.2 [Content share options fill up](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2256).
3.3 [Start content share](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2260).
3.4 [Handle content start](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2301).
3.5 [Bind video tile in VideoTileDidUpdate](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2567).
> Note: Similarly you will find pause, unpause and stopping content share implementation in the Amazon Chime JS SDK demo.

Please let us know if you have any issue.

**Comment by reynoldnathaniel** [comment]
Thank you so much for your reply @devalevenkatesh ! 
Just a suggestion to Amazon Chime team, I think Chime SDK can build some kind of an API that can automatically record the whole meeting and put into S3. It would be great because with that integration, a lot of partners and customers can do automatic video analytics/sentiment analysis easily through S3 trigger. Hope this is a good feedback for Chime team! Cheers!

**Comment by reynoldnathaniel** [comment]
@devalevenkatesh 
Will re-close again
