### ISSUE TITLE
Readme should reference Lex Console V1 for import

### ISSUE THREAD

**Issue by mdebusschere** [aws-samples/amazon-chime-sdk-amazon-connect-integration-demo#8]
Tried to import StartVideoCall Amazon Lex Bot per Customer Setup Step 1 instructions.
The default console was Lex V2 Console.   The import failed when using Lex V2 Console.
Switched to Lex V1 and it worked per the README.

Suggest adding comment to README or resolving import issue with Console V2.

**Comment by devalevenkatesh** [comment]
Thanks for trying out the demo and providing suggestions to improve the README.

Just checking if all steps worked fine for you later and you were able to run the demo, right? It has been a while this demo is updated hence checking if we need to address more here.

**Comment by mdebusschere** [comment]
The  npm install steps for Customer and Agent had dependency issues which I had to override,  didn't bother sorting out.
Had issue with Agent web app..  it couldn't start the CCP which was being redirected back to the login page despite having page
with CCP already logged in.. not sure if it's a CORs issue.   Haven't had time to pick it back up.

**Comment by vaoneiler** [comment]
I had the same issue with uploading StartVideoCall...LEX_V1.zip file.

**Comment by vaoneiler** [comment]
Hi, when I invoke npm run start I keep getting "compiled with warnings" on both agent and customer and nothing happens:
I have gone over this twice and made sure I checked everything. Please assist

CUSTOMER:
WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/customer/index.html 3.32 KiB {0} [built]
    [1] ./node_modules/lodash/lodash.js 531 KiB {0} [built]
    [2] (webpack)/buildin/global.js 472 bytes {0} [built]
    [3] (webpack)/buildin/module.js 497 bytes {0} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!src/style.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js!./src/style.css 9.56 KiB {0} [built]
    [1] ./node_modules/css-loader/dist/runtime/api.js 2.46 KiB {0} [built]
ℹ ｢wdm｣: Compiled with warnings.

AGENT:
WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child HtmlWebpackCompiler:
                      Asset       Size  Chunks             Chunk Names
        assets/hang-off.svg   1.05 KiB          [emitted]  
             assets/mic.svg  632 bytes          [emitted]  
    assets/screen-share.svg  462 bytes          [emitted]  
          assets/volume.svg   1.29 KiB          [emitted]  
     + 1 hidden asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/agent/index.html 2.67 KiB {0} [built]
    [1] ./node_modules/html-loader/dist/runtime/getUrl.js 548 bytes {0} [built]
    [2] ./src/assets/mic.svg 58 bytes {0} [built]
    [3] ./src/assets/volume.svg 61 bytes {0} [built]
    [4] ./src/assets/screen-share.svg 67 bytes {0} [built]
    [5] ./src/assets/hang-off.svg 63 bytes {0} [built]
ℹ ｢wdm｣: Compiled with warnings.

**Comment by vaoneiler** [comment]
Initially npm run start was not launching windows but I had to kill previous processes. Now both the agent(CCP) and the customer windows are coming up... However the customer window only shows a blue icon at bottom of screen with "speak to agent" the "end chat". I thought I would have to enter word "chat" or "video". There is No connectivity.

**Comment by mdebusschere2** [comment]
Have you viewed the console logs in the browser?   I rely heavily on the console logs for both customer and agent side.

**Comment by devalevenkatesh** [comment]
Hi @vaoneiler ,

Thanks for reporting the issue, could you please create a separate issue with some logs or screenshots of your error? Since this is for README lex issue just want to keep it separate. Closing this issue now. Sorry for the inconvenience.
